config/routes.rb
Rails.application.routes.draw do
  # get 'reviews/new'
  # get 'products/index'
  root to: "pages#home"

  devise_for :users
  get 'users/show'

  devise_scope :user do
    resources :users, only: [:show] do
      resources :reviews, only: [:new, :create]
    end
  end

  resources :products do
    resources :offers, only: [:new, :create, :show, :index] do
      resources :chatrooms, only: [:show] do
        # resources :messages, only: [:create]
      end
    end
  end

  resources :offers, only: [:show] do
    resources :messages, only: [:create]
    member do
      put :accept
      put :refuse
    end
  end
  resources :offers, only: [:destroy, :edit]
  resources :messages, only: [:destroy, :edit]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/product.rb
class Product < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?



  has_many_attached :photos

  belongs_to :user
  has_many :offers, dependent: :destroy
  # has_many :offered_products, class_name: 'Product', foreign_key: "offered_product_id"
  has_many :offered_offers, class_name: 'Offer', foreign_key: 'offered_product_id', dependent: :destroy

  validates :title, :description, :quality, presence: true

  include PgSearch::Model
  pg_search_scope :search,
                  against: [:title, :description, :category, :subcategory, :address, :quality],
                  using: {
                    tsearch: { prefix: true }
                  }

  pg_search_scope :filter_category,
                  against: [:category],
                  using: {
                    tsearch: { prefix: true }
                  }

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :set_rating, only: [:show]
  skip_before_action :authenticate_user!, only: [ :index, :show ]

  # before_action :product_params, only: [:new]

  def index
    # raise
    # @products = Product.joins("LEFT JOIN offers ON products.id = offers.product_id OR products.id = offers.offered_product_id")
    #                    .where("offers.deal IS NULL OR offers.deal = ?", false)
    #                    .distinct
    @products = case params[:category]
                when 'service'
                  Product.where("category= ? AND bartered= ?", 'service', false)
                when 'goods'
                  Product.where("category= ? AND bartered= ?", 'goods', false)
                else
                  Product.where("bartered = ?", false)
                end
    if params[:query].present?
      @products = @products.search(params[:query])
    end
    if @products.empty?
      flash[:notice] = "There are no products!"
    end
  end

  def show
    # @product = Product.find_by(id: params[:id])
    @markers = [
      {
        lat: @product.latitude,
        lng: @product.longitude
      }
    ]
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.user = current_user
    if @product.save
      redirect_to product_path(@product)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit

  end

  def update
    if @product.update(product_params)
      redirect_to @product
    else
      render :form, status: :unprocessable_entity
    end
  end

  def destroy
    @product.destroy
    redirect_to current_user, status: :see_other
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:title, :description, :quality, :category, :address, :subcategory, photos: [])
  end

  def filter_category
    @products = @products.filter_category(params[:query])
  end


  def set_rating

    @user_rating = 0
    if @product.user.rated_reviews.size.zero?
      @user_rating = 0
    else
      @product.user.rated_reviews.each do |review|
        @user_rating += review.rating
      end

      @user_rating /= @product.user.rated_reviews.size.to_f
      @user_rating = (@user_rating * 2.0).round / 2.0
    end
  end
end

app/views/products/_form.html.erb
<div class="d-flex justify-content-center">
  <%= simple_form_for @product, data: { controller: 'product-form' } do |f| %>
      <%= f.input :title, placeholder: "Title", input_html: { class: 'form-control' } %>
      <%= f.input :description, placeholder: "Describe your product", input_html: { class: 'form-control' } %>
      <%= f.input :category, collection: ['service', 'goods'], prompt: 'Select a category',
        input_html: { id: 'category-select', data: { product_form_target: 'categorySelect', action: 'change->product-form#updateSubcategories' }, class: 'form-control' } %>
      <%= f.input :subcategory, collection: [], prompt: 'Select a subcategory',
        input_html: { id: 'subcategory-select', disabled: true, data: { product_form_target: 'subcategorySelect' }, class: 'form-control' } %>
      <%= f.input :quality, placeholder: "Quality", input_html: { class: 'form-control' } %>
      <%= f.input :address, placeholder: "Address", input_html: { class: 'form-control', autocomplete: "street-address" } %>
      <%= f.input :photos, as: :file, input_html: { multiple: true, class: 'form-control' } %>

      <%= f.submit class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/products/_index.html.erb
<div data-controller="search_products">
<%# Search bar %>
  <div class="d-flex justify-content-center my-4">
    <%= form_with url: products_path, method: :get, html: { class: "d-flex justify-content-center",
      data: { search_products_target: "form" } } do |form| %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control new-search",
        placeholder: "Find a product or address",
        data: { search_products_target: "input" }
      %>
        <%= radio_button_tag "category", "service" %>
          <%= label "service", "service" %>
        <%= radio_button_tag "category", "goods" %>
          <%= label "goods", "goods" %>
        <%= radio_button_tag "category", "all" %>
          <%= label "all", "all" %>
      <%= submit_tag "Search", class: "abtn" %>
    <% end %>
    <%# <div class="d-flex justify-content-center align-center ms-3"> %>
      <%# <%= link_to 'Add a product', new_product_path, class: 'abtn' %>
    <%# </div> %>
  </div>
  <%= render "products/products_list", products: @products %>
</div>

app/views/products/_products_list.html.erb
    <div class="row gap-3 justify-content-center" id='products' data-search-products-target="list">
      <% @products.each do |product| %>
          <div class= "card col-sm-6 col-md-3 col-lg-2 px-0">
            <% if product.photos.first %>
              <%= link_to product, style:"height:100%" do %>
                    <%= cl_image_tag product.photos.first.key, class: 'card-img-top product-img', style:"height:100%; max-height: 146px" %>
              <% end %>
            <%end%>
            <div class="card-body d-flex flex-column justify-content-end">
              <p class='text-center product-title'><%= link_to product.title.capitalize , product_path(product), class: 'text-decoration-none' %></p>
              <div class="d-flex justify-content-between">
                <p class="username"><small><i class="fa-solid fa-user"></i> <%= link_to product.user.name, product.user %></small></p>
                <p><small><strong>Quality:</strong> <%= product.quality.capitalize %></small></p>
              </div>
            </div> <%# card body %>

          </div> <%# card div %>
        <%# card container %>
      <% end %>
    </div> <%# row %>

app/views/products/edit.html.erb
  <h3 class='display-6 text-center mt-3'>Edit a Product</h3>
  <%= render "form", product: @product %>

app/views/products/index.html.erb
<h3 class='display-6 text-center m-4'>All Products</h3>
<%= render "index" %>

app/views/products/new.html.erb
  <h3 class='display-6 text-center mt-3'>Upload a new Product</h3>
  <%= render "form", product: @product %>

app/views/products/show.html.erb
<%# Code to display the product details and its images in a carousel %>
    <div class="pic-title">
      <h1 class="product-title text-center"><strong><%= @product.title.capitalize %></strong></h1>
      <div class="barter-button-container">
        <p class="username"><i class="fa-solid fa-user"></i> <%= link_to @product.user.name, @product.user, class:"username" %></p>
        <div class="barter_button">
          <% if @product.user != current_user %>
            <strong><%= link_to "barter", new_product_offer_path(@product), class:"button pulse" %></strong>
          <% end %>
        </div>
      </div>
    </div>
    <div class="product-up row flex-nowrap">
    <div class="page-left col-4">
      <%# <div class="main-pic" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @product.photos.first.key, height: 500, crop: :fill %>
      <div class="main-pic">
        <%if @product.photos.first %>
        <%= cl_image_tag  @product.photos.first.key, height: 400, crop: :fill, style: "object-fit: cover"%>
        <%end%>
      </div>

      <div class="small-pics">
        <% @product.photos.each_with_index do |photo, index| %>
          <%if photo %>
          <button data-bs-toggle="modal" data-bs-target="#pictureModal-<%=index%>" data-controller="modal">
            <%= cl_image_tag photo.key, height: 50, width: 80, crop: :fill, data_bs_toggle:"modal", data_bs_target:"#pictureModal-#{index}", data_controller:"modal" %>
          </button>
          <%end%>
          <div class="modal fade" id="pictureModal-<%=index%>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" data-controller="modal">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
              <%if photo %>
                <%= cl_image_tag photo.key, height: 500, width: 700, crop: :fill, data_bs_toggle:"modal", data_bs_target:"#exampleModal", data_controller:"modal" %>
              <%end%>
              </div>
            </div>
          </div>
        <%end%>
      </div>
    </div>
    <div class="page-right col-6">
      <div class="accordion" id="accordionPanelsStayOpenExample">
        <div class="accordion-item">
          <h2 class="accordion-header" id="panelsStayOpen-headingOne">
            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="true" aria-controls="panelsStayOpen-collapseOne">
              <strong>Description</strong>
            </button>
          </h2>
          <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse show" aria-labelledby="panelsStayOpen-headingOne">
            <div class="accordion-body">
              <%= @product.description %> <p><%= @product.category %> : <%= @product.subcategory %></p>
              <p><strong>Address:</strong> <%= @product.address %></p>

            </div>
          </div>
        </div>
        <div class="accordion-item">
          <h2 class="accordion-header" id="panelsStayOpen-headingTwo">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="false" aria-controls="panelsStayOpen-collapseTwo">
              <strong>Quality</strong>
            </button>
          </h2>
          <div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingTwo">
            <div class="accordion-body">
            <%= @product.quality %>
            </div>
          </div>
        </div>
        <div class="accordion-item">
          <h2 class="accordion-header" id="panelsStayOpen-headingThree">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseThree" aria-expanded="false" aria-controls="panelsStayOpen-collapseThree">
              <div class="d-flex justify-content-end">
                <strong>User Rating</strong>
                <% if @product.user.rated_reviews.blank? %>
                  <p class='text-center'><em> No reviews yet! </em></p>
                <% else %>
                  <%= '⭐' * @user_rating %>
                <% end %>
              </div>

            </button>
          </h2>
          <div id="panelsStayOpen-collapseThree" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingThree">
            <div class="accordion-body">
              <% if @product.user.rated_reviews.blank? %>
                <h5 class='text-center'> <strong><%= link_to @product.user.first_name.capitalize, @product.user %></strong><em> has no reviews! </h5></em>
              <% else %>

                <ul class="list-group">
                  <% @product.user.rated_reviews.each do |review| %>
                    <li class="list-group-item"><%= link_to review.reviewer.username, user_path(review.reviewer) %>: <%= review.content %>
                      <strong><%= '⭐' * review.rating %></strong>
                    </li>
                  <% end %>
                </ul>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="product-map" style="width: 100%">
        <div style="width: 100%; height: 300px;"
          data-controller="map"
          data-map-markers-value="<%= @markers.to_json %>"
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>

      <div class="product-action">


        <% if @product.user == current_user %>
          <p><%= link_to 'Edit Product', edit_product_path, class: 'btn btn-outline-success' %></p>

          <p><%= link_to "Delete Product",
                  product_path(@product),
                  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
                  class: 'btn btn-outline-warning'
                  %></p>

        <% end %>
      </div>
    </div>
  </div>